#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Corpus computing with Text-Fabric  # The title of the book. Will be placed in the left navbar.
author                      : Dirk Roorda  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : tf.png  # A path to the book logo

only_build_toc_files: true

repository:
  url: https://github.com/annotation/book
html:
  favicon: tf-small.png
  use_repository_button: true
  use_issues_button: true

execute:
  execute_notebooks: off
  timeout: 120

launch_buttons:
  notebook_interface: jupyterlab
